{{- if and .Values.redis.enabled .Values.redis.persistence.enabled (not .Values.redis.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spotizerr.redis.fullname" . }}
  labels:
    {{- include "spotizerr.redis.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.redis.persistence.accessMode }}
  {{- if .Values.redis.persistence.storageClassName }}
  storageClassName: {{ .Values.redis.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}

