{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spotizerr.redis.fullname" . }}
  labels:
    {{- include "spotizerr.redis.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "spotizerr.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/redis-secret.yaml") . | sha256sum }}
      labels:
        {{- include "spotizerr.redis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        command:
        - sh
        - -c
        - |
          redis-server \
            --requirepass "$REDIS_PASSWORD" \
            {{- if .Values.redis.args.appendonly }}
            --appendonly yes
            {{- end }}
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "spotizerr.redis.secretName" . }}
              key: {{ .Values.redis.existingSecretPasswordKey }}
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        {{- if .Values.redis.persistence.enabled }}
        - name: redis-data
          mountPath: /data
        {{- end }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
      volumes:
      {{- if .Values.redis.persistence.enabled }}
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ .Values.redis.persistence.existingClaim | default (include "spotizerr.redis.fullname" .) }}
      {{- end }}
{{- end }}

