{{- if .Values.spotizerr.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spotizerr.secretName" . }}
  labels:
    {{- include "spotizerr.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.spotizerr.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}

