apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotizerr.fullname" . }}
  labels:
    {{- include "spotizerr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.spotizerr.service.type }}
  ports:
  - port: {{ .Values.spotizerr.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "spotizerr.selectorLabels" . | nindent 4 }}

