---
# Critical volumes - Daily backups at 2 AM
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-critical-daily
  namespace: longhorn
spec:
  cron: "0 2 * * *"
  task: "backup"
  groups:
    - critical
  retain: 30
  concurrency: 2
  labels:
    job-type: backup
    priority: critical
---
# Important volumes - Weekly backups on Sunday at 3 AM
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-important-weekly
  namespace: longhorn
spec:
  cron: "0 3 * * 0"
  task: "backup"
  groups:
    - important
  retain: 12
  concurrency: 2
  labels:
    job-type: backup
    priority: important
---
# Nice-to-have volumes - Weekly backups on Saturday at 4 AM
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-optional-weekly
  namespace: longhorn
spec:
  cron: "0 4 * * 6"
  task: "backup"
  groups:
    - optional
  retain: 7
  concurrency: 1
  labels:
    job-type: backup
    priority: optional
---
# Critical snapshots - Every 6 hours for quick recovery
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-critical-6h
  namespace: longhorn
spec:
  cron: "0 */6 * * *"
  task: "snapshot"
  groups:
    - critical
  retain: 8
  concurrency: 3
  labels:
    job-type: snapshot
    priority: critical

