---
longhorn:
  helmPreUpgradeCheckerJob:
    enabled: false
  preUpgradeChecker:
    jobEnabled: false
    upgradeVersionCheck: false
  
  # Cloudflare R2 backup configuration
  defaultBackupStore:
    backupTarget: s3://sabkhi-lab-backups@auto/
    backupTargetCredentialSecret: longhorn-r2-secret
    pollInterval: 300
  
  defaultSettings:
    # Fail if backup fails
    allowRecurringJobWhileVolumeDetached: false
    # Concurrent backup jobs
    backupConcurrentLimit: 2
    # Restore concurrency
    restoreConcurrentLimit: 2
    # Compression method
    backupCompressionMethod: lz4
    # Backup execution timeout (hours)
    backupExecutionTimeout: 1
    # Failed backup TTL (minutes)
    failedBackupTTL: 1440
  
  ingress:
    enabled: true
    ingressClassName: nginx
    host: longhorn.internal.rmsz005.com
    tls: true
    tlsSecret: longhorn-tls
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      cert-manager.io/common-name: "longhorn.internal.rmsz005.com"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"