---
deploymentMode: SingleBinary

loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095
    http_server_read_timeout: 310s
    http_server_write_timeout: 310s
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  limits_config:
    ingestion_rate_mb: 16
    ingestion_burst_size_mb: 32
    max_query_length: 721h
    max_query_parallelism: 32
  compactor:
    working_directory: /var/loki/retention

singleBinary:
  replicas: 1
  resources:
    requests:
      memory: "550Mi"
      cpu: "25m"
    limits:
      memory: "1100Mi"
      cpu: "100m"
  persistence:
    enabled: true
    size: 50Gi
    storageClass: "longhorn-nvme-replicated"
  extraPorts:
    - name: metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics

service:
  type: ClusterIP
  port: 3100
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
    prometheus.io/path: "/metrics"

gateway:
  enabled: false

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  serviceMonitor:
    enabled: true
    interval: 30s

test:
  enabled: false

lokiCanary:
  enabled: false
