openspeedtest:
  # Replica count
  replicaCount: 1

  # Image configuration
  image:
    repository: openspeedtest/latest
    pullPolicy: Always
    tag: "v2.0.6"

  # Service configuration
  service:
    type: ClusterIP
    port: 3000

  # Ingress configuration
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      # Force HTTP/1.1 and disable all compression
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/server-snippet: |
        gzip off;
        gzip_proxied off;
        gunzip off;
    hosts:
      - host: speedtest.internal.rmsz005.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: speedtest-tls
        hosts:
          - speedtest.internal.rmsz005.com

  # Resources
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

