---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-ephemeral-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  hostPath:
    path: /tmp/immich-ephemeral
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ephemeral-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
