---
# Bitwarden Self-Host Configuration
# Managed by ArgoCD

general:
  domain: "bitwarden.internal.rmsz005.com"
  
  ingress:
    enabled: true
    className: "nginx"
    
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      cert-manager.io/common-name: "bitwarden.internal.rmsz005.com"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/proxy-body-size: "105m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    
    tls:
      name: bitwarden-tls
      clusterIssuer: letsencrypt
  
  # Disable open registration - admin only
  disableUserRegistration: "true"
  
  # Admin email (comma-separated for multiple)
  admins: "ramzy.sabkhi@gmail.com"
  
  email:
    replyToEmail: "bitwarden@rmsz005.com"
    smtpHost: "smtp-relay.brevo.com"
    smtpPort: "587"
    smtpSsl: "false"  # Using STARTTLS
    smtpTrustServer: "false"
    smtpSslOverride: "false"
    smtpStartTls: "true"  # Force STARTTLS
  
  # Use ReadWriteOnce for better compatibility with Longhorn
  volumeAccessMode: "ReadWriteOnce"
  
  # Disable cloud communication (self-hosted only)
  enableCloudCommunication: false

# Built-in SQL Server configuration
database:
  enabled: true  # Use built-in SQL Server
  
  # SQL Server 2022 image
  image:
    name: mcr.microsoft.com/mssql/server
    tag: 2022-CU12-ubuntu-22.04
  
  # Resources for SQL Server
  resources:
    requests:
      memory: "2Gi"
      cpu: "100m"
    limits:
      memory: "4Gi"
      cpu: "1000m"
  
  # PVC configuration for SQL Server
  volume:
    data:
      size: 10Gi
      storageClass: "longhorn-ssd-replicated"
      accessMode: ReadWriteOnce
    
    log:
      size: 10Gi
      storageClass: "longhorn-ssd-replicated"
      accessMode: ReadWriteOnce
    
    backups:
      size: 5Gi
      storageClass: "longhorn-hd-replicated"
      accessMode: ReadWriteOnce

# Shared storage for attachments
sharedStorageClassName: "longhorn-hd-replicated"

# Component-specific overrides
component:
  admin:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 500m
  
  api:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 1000m
  
  attachments:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  events:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  icons:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  identity:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 500m
  
  notifications:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  scim:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  sso:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  web:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m

# Secrets configuration
# All sensitive data comes from bitwarden-secrets sealed secret
secrets:
  secretName: bitwarden-secrets
  secretProviderClass: ""
