---
# Bitwarden Self-Host Configuration
# Chart: bitwarden/self-host v2025.10.0
# Managed by ArgoCD

general:
  domain: "bitwarden.internal.rmsz005.com"
  
  ingress:
    enabled: true
    className: "nginx"
    
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "105m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    
    # Certificate configuration for cert-manager
    cert:
      tls:
        name: bitwarden-tls
        clusterIssuer: letsencrypt
  
  # Disable open registration - admin only
  disableUserRegistration: "true"
  
  # Admin email (comma-separated for multiple)
  admins: "ramzy.sabkhi@gmail.com"
  
  # Email configuration (Brevo SMTP)
  email:
    replyToEmail: "bitwarden@rmsz005.com"
    smtpHost: "smtp-relay.brevo.com"
    smtpPort: "587"
    smtpSsl: "false"  # Using STARTTLS
    smtpTrustServer: "false"
    smtpSslOverride: "false"
    smtpStartTls: "true"  # Force STARTTLS
  
  # Use ReadWriteOnce (Longhorn only supports RWO, not RWX)
  # Each volume can be accessed by one pod at a time
  volumeAccessMode: "ReadWriteOnce"
  
  # Disable cloud communication (fully self-hosted)
  # Set to true if you want billing/license sync with Bitwarden cloud
  enableCloudCommunication: false
  cloudRegion: "US"

# Shared storage class (Longhorn HDD tier for attachments/licenses/logs)
# Note: Longhorn only supports ReadWriteOnce, so we override volumeAccessMode above
sharedStorageClassName: "longhorn-hd-replicated"

# Built-in SQL Server configuration
database:
  enabled: true  # Use built-in SQL Server pod
  
  # SQL Server 2022 image (latest CU)
  image:
    name: mcr.microsoft.com/mssql/server
    tag: 2022-CU12-ubuntu-22.04
  
  # Resources for SQL Server
  resources:
    requests:
      memory: "2Gi"
      cpu: "100m"
    limits:
      memory: "4Gi"
      cpu: "1000m"
  
  # PVC configuration for SQL Server
  volume:
    data:
      size: 10Gi
      storageClass: "longhorn-ssd-replicated"
      accessMode: ReadWriteOnce
    
    log:
      size: 10Gi
      storageClass: "longhorn-ssd-replicated"
      accessMode: ReadWriteOnce
    
    backups:
      size: 5Gi
      storageClass: "longhorn-hd-replicated"
      accessMode: ReadWriteOnce

# Secrets configuration
# Required secrets (must be created via sealed-secrets):
# - globalSettings__installation__id: From https://bitwarden.com/host
# - globalSettings__installation__key: From https://bitwarden.com/host
# - globalSettings__mail__smtp__username: SMTP username (Brevo)
# - globalSettings__mail__smtp__password: SMTP password (Brevo)
# - SA_PASSWORD: SQL Server SA password (must be strong!)
# Optional but recommended:
# - globalSettings__yubico__clientId: YubiKey client ID
# - globalSettings__yubico__key: YubiKey secret key
# - globalSettings__hibpApiKey: HaveIBeenPwned API key
secrets:
  secretName: bitwarden-secrets
  secretProviderClass: ""

# Volume overrides for specific components
volume:
  attachments:
    size: 5Gi
    storageClass: "longhorn-hd-replicated"
    accessMode: ReadWriteOnce
  
  licenses:
    size: 1Gi
    storageClass: "longhorn-hd-replicated"
    accessMode: ReadWriteOnce
  
  # Enable logs volume for troubleshooting
  logs:
    enabled: true
    size: 2Gi
    storageClass: "longhorn-hd-replicated"
    accessMode: ReadWriteOnce

# Component-specific resource limits
component:
  admin:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 500m
  
  api:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 1000m
  
  attachments:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  events:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  icons:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  identity:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 500m
  
  notifications:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  scim:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  sso:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
  
  web:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m

