apiVersion: v2
name: policy-reporter
description: Wrapper chart for Policy Reporter with ingress configuration
type: application
version: 0.1.0
dependencies:
  - name: policy-reporter
    version: 3.*
    repository: https://kyverno.github.io/policy-reporter/
