---
planeVersion: "v1.0.0"

ingress:
  enabled: true
  appHost: "plane.internal.rmsz005.com"
  minioHost: ""
  rabbitmqHost: ""
  ingressClass: "nginx"
  ingress_annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt"
    cert-manager.io/common-name: "plane.internal.rmsz005.com"

ssl:
  generateCerts: false
  createIssuer: false
  tls_secret_name: "plane-tls"

redis:
  local_setup: true
  image: valkey/valkey:7.2.11-alpine
  servicePort: 6379
  storageClass: "longhorn-ssd-replicated"
  volumeSize: 500Mi
  pullPolicy: IfNotPresent
  assign_cluster_ip: false

postgres:
  local_setup: true
  image: postgres:15.14-alpine
  servicePort: 5432
  storageClass: "longhorn-ssd-replicated"
  volumeSize: 5Gi
  pullPolicy: IfNotPresent
  assign_cluster_ip: false

rabbitmq:
  local_setup: true
  image: rabbitmq:3.13.7-management-alpine
  pullPolicy: IfNotPresent
  servicePort: 5672
  managementPort: 15672
  storageClass: "longhorn-ssd-replicated"
  volumeSize: 500Mi
  assign_cluster_ip: false

minio:
  image: minio/minio:latest
  image_mc: minio/mc:latest
  local_setup: true
  pullPolicy: IfNotPresent
  storageClass: "longhorn-ssd-replicated"
  volumeSize: 10Gi
  assign_cluster_ip: false
  env:
    minio_endpoint_ssl: false

web:
  replicas: 1
  memoryLimit: 4Gi
  cpuLimit: 8000m
  cpuRequest: 250m
  memoryRequest: 100Mi
  image: artifacts.plane.so/makeplane/plane-frontend
  pullPolicy: Always
  assign_cluster_ip: false

space:
  replicas: 1
  memoryLimit: 4Gi
  cpuLimit: 8000m
  cpuRequest: 250m
  memoryRequest: 100Mi
  image: artifacts.plane.so/makeplane/plane-space
  pullPolicy: Always
  assign_cluster_ip: false

admin:
  replicas: 1
  memoryLimit: 4Gi
  cpuLimit: 8000m
  cpuRequest: 250m
  memoryRequest: 100Mi
  image: artifacts.plane.so/makeplane/plane-admin
  pullPolicy: Always
  assign_cluster_ip: false

live:
  replicas: 1
  memoryLimit: 8Gi
  cpuLimit: 8000m
  cpuRequest: 250m
  memoryRequest: 320Mi
  image: artifacts.plane.so/makeplane/plane-live
  pullPolicy: Always
  assign_cluster_ip: false

api:
  replicas: 1
  memoryLimit: 8Gi
  cpuLimit: 16000m
  cpuRequest: 800m
  memoryRequest: 200Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always
  assign_cluster_ip: false

worker:
  replicas: 1
  memoryLimit: 16Gi
  cpuLimit: 8000m
  cpuRequest: 250m
  memoryRequest: 850Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always

beatworker:
  replicas: 1
  memoryLimit: 4Gi
  cpuLimit: 8000m
  cpuRequest: 250m
  memoryRequest: 200Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always

external_secrets:
  rabbitmq_existingSecret: 'plane-rabbitmq-secret'
  pgdb_existingSecret: 'plane-pgdb-secret'
  doc_store_existingSecret: 'plane-docstore-secret'
  app_env_existingSecret: 'plane-app-env-secret'
  live_env_existingSecret: 'plane-live-env-secret'

env:
  pgdb_username: plane
  pgdb_name: plane
  docstore_bucket: "uploads"
  doc_upload_size_limit: "52428800"
  cors_allowed_origins: "https://plane.internal.rmsz005.com"
  api_key_rate_limit: "60/minute"
  default_cluster_domain: cluster.local

