---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-tailscale
  namespace: ess
  annotations:
    tailscale.com/tags: "tag:matrix"
spec:
  ingressClassName: tailscale
  rules:
  - host: chat
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ess-element-web
            port:
              number: 80
  tls:
  - hosts:
    - chat


