---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-tailscale
  namespace: immich
  annotations:
    tailscale.com/tags: "tag:immich"
    tailscale.com/hostname: "immich.internal.rmsz005.com"
spec:
  ingressClassName: tailscale
  rules:
  - host: immich.internal.rmsz005.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich-server
            port:
              number: 2283
  tls:
  - hosts:
    - immich.internal.rmsz005.com

