---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plane-tailscale
  namespace: plane
  annotations:
    tailscale.com/tags: "tag:k8s"
spec:
  ingressClassName: tailscale
  rules:
  - host: plane
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: plane-api-clusterip
            port:
              number: 8000
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: plane-api-clusterip
            port:
              number: 8000
      - path: /live/
        pathType: Prefix
        backend:
          service:
            name: plane-live-clusterip
            port:
              number: 3000
      - path: /spaces
        pathType: Prefix
        backend:
          service:
            name: plane-space-clusterip
            port:
              number: 3000
      - path: /god-mode
        pathType: Prefix
        backend:
          service:
            name: plane-admin-clusterip
            port:
              number: 3000
      - path: /uploads
        pathType: Prefix
        backend:
          service:
            name: plane-minio-clusterip
            port:
              number: 9000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plane-web-clusterip
            port:
              number: 3000
  tls:
  - hosts:
    - plane

