---
# ServiceMonitor for Immich Server
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: immich-server
  namespace: monitoring
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server
spec:
  namespaceSelector:
    matchNames:
      - immich
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: immich
  endpoints:
    - port: metrics-api
      path: /metrics
      interval: 30s
