---
# Navidrome Helm Chart Values for sabkhi_lab
# Chart: djjudas21/navidrome v6.7.5 (uses bjw-s common library)
# Navidrome App Version: 0.58.0

# Image configuration
image:
  repository: deluan/navidrome
  tag: "0.58.0"
  pullPolicy: IfNotPresent

# Environment variables for Navidrome configuration
# See: https://www.navidrome.org/docs/usage/configuration-options/#environment-variables
env:
  # Timezone
  TZ: UTC
  
  # Logging and session
  ND_LOGLEVEL: info
  ND_SESSIONTIMEOUT: 24h
  
  # Music folder (mounted at /app/downloads via persistence, shared with Spotizerr)
  ND_MUSICFOLDER: /app/downloads
  
  # Scanner settings
  ND_SCANSCHEDULE: "@every 1h"
  ND_AUTOIMPORTPLAYLISTS: "true"
  
  # Transcoding settings
  ND_ENABLETRANSCODINGCONFIG: "true"
  ND_TRANSCODINGCACHESIZE: "100MB"
  
  # UI settings
  ND_ENABLEGRAVATAR: "true"
  ND_UILOGINBACKGROUNDURL: ""
  ND_UIWELCOMEMESSAGE: ""
  
  # Features
  ND_LASTFM_ENABLED: "true"
  ND_ENABLESHARING: "false"
  
  # Prometheus metrics (disabled by default)
  ND_PROMETHEUS_ENABLED: "false"
  
  # Spotify integration (set via sealed secret if needed)
  # ND_SPOTIFY_ID: ""
  # ND_SPOTIFY_SECRET: ""

# Service configuration
service:
  main:
    ports:
      http:
        port: 4533
    monitor:
      enabled: false
      endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 1m
          scrapeTimeout: 10s

# Ingress configuration
ingress:
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      # Explicitly remove the insecure configuration-snippet from chart defaults
      nginx.ingress.kubernetes.io/configuration-snippet: null
      cert-manager.io/cluster-issuer: "letsencrypt"
      cert-manager.io/common-name: "navidrome.internal.rmsz005.com"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    hosts:
      - host: navidrome.internal.rmsz005.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: navidrome-tls
        hosts:
          - navidrome.internal.rmsz005.com

# Persistence configuration
persistence:
  # Config/data volume (database, cache, etc.)
  config:
    enabled: true
    type: pvc
    mountPath: /data
    storageClass: longhorn-ssd-replicated
    accessMode: ReadWriteOnce
    size: 5Gi
    retain: true
    annotations:
      recurring-job.longhorn.io/source: enabled
      recurring-job-group.longhorn.io/important: enabled
  
  # Music library volume - shared with Spotizerr via music-library PVC
  music:
    enabled: true
    type: pvc
    mountPath: /app/downloads  # Matches Spotizerr's download path
    existingClaim: "music-library"  # Shared music library PVC (media namespace)
    # storageClass, accessMode, size ignored when using existingClaim
    retain: true

# Resource limits
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

# Security context
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Probes (using bjw-s common chart format)
probes:
  liveness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /
        port: 4533
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
  
  readiness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /
        port: 4533
      initialDelaySeconds: 30
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3

# Controller settings
controller:
  replicas: 1
  strategy: Recreate  # Only one replica can access PVC at a time

# Additional pod annotations
podAnnotations: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity rules
affinity: {}