---
immich:
  persistence:
    library:
      existingClaim: "immich-library-pvc"

image:
  tag: "v2.0.1"

postgresql:
  enabled: false

env:
  DB_HOSTNAME: "immich-postgresql"
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"
  REDIS_HOSTNAME: "immich-redis-master"
  REDIS_PORT: "6379"
  NODE_ENV: "production"
  LOG_LEVEL: "log"
  FFMPEG_THREADS: "0"
  IMMICH_TELEMETRY_INCLUDE: "all"
  IMMICH_API_METRICS_PORT: "8081"
  IMMICH_MICROSERVICES_METRICS_PORT: "8082"
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-postgresql-secret
        key: password
  REDIS_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-redis-secret
        key: password

server:
  controller:
    replicas: 2
  service:
    main:
      ports:
        metrics-api:
          enabled: true
          port: 8081
          protocol: TCP
          targetPort: 8081
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        cert-manager.io/cluster-issuer: "letsencrypt"
        cert-manager.io/common-name: "immich.internal.rmsz005.com"
      hosts:
        - host: immich.internal.rmsz005.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - immich.internal.rmsz005.com
          secretName: immich-tls
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "8Gi"
      cpu: "4000m"

machine-learning:
  controller:
    replicas: 2
  service:
    main:
      ports:
        metrics:
          enabled: true
          port: 8082
          protocol: TCP
          targetPort: 8082
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "8Gi"
      cpu: "4000m"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - immich
        topologyKey: kubernetes.io/hostname

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: immich-redis-secret
    existingSecretPasswordKey: password
  master:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: "longhorn-ssd-replicated"
    resources:
      requests:
        memory: 100Mi
        cpu: 110m
      limits:
        memory: 200Mi
        cpu: 250m
