---
immich:
  persistence:
    library:
      existingClaim: "immich-library-pvc"

image:
  tag: "v2.0.1"

postgresql:
  enabled: false

env:
  DB_HOSTNAME: "immich-postgresql"
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"
  REDIS_HOSTNAME: "immich-redis-master"
  REDIS_PORT: "6379"
  NODE_ENV: "production"
  LOG_LEVEL: "log"
  FFMPEG_THREADS: "0"
  IMMICH_TELEMETRY_INCLUDE: "all"
  IMMICH_API_METRICS_PORT: "8081"
  IMMICH_MICROSERVICES_METRICS_PORT: "8082"
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-postgresql-secret
        key: password
  REDIS_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-redis-secret
        key: password

server:
  controller:
    replicas: 2
  service:
    main:
      ports:
        metrics-api:
          enabled: true
          port: 8081
          protocol: TCP
          targetPort: 8081
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        cert-manager.io/cluster-issuer: "letsencrypt"
        cert-manager.io/common-name: "immich.internal.rmsz005.com"
      hosts:
        - host: immich.internal.rmsz005.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - immich.internal.rmsz005.com
          secretName: immich-tls
  resources:
    requests:
      memory: "1200Mi"
      cpu: "200m"
  nodeSelector:
    gpu: nvidia
  env:
    IMMICH_MEDIA_FFMPEG_ACCEL: "nvenc"
    IMMICH_MEDIA_FFMPEG_ACCEL_DECODE: "cuda"

machine-learning:
  controller:
    replicas: 1
  service:
    main:
      ports:
        metrics:
          enabled: true
          port: 8082
          protocol: TCP
          targetPort: 8082
  resources:
    requests:
      memory: "1000Mi"
      cpu: "50m"
      nvidia.com/gpu: "1"
    limits:
      nvidia.com/gpu: "1"
  nodeSelector:
    gpu: nvidia
  env:
    MACHINE_LEARNING_DEVICE: "cuda"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - immich
            - key: app.kubernetes.io/component
              operator: In
              values:
              - machine-learning
          topologyKey: kubernetes.io/hostname

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: immich-redis-secret
    existingSecretPasswordKey: password
  master:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: "longhorn-ssd-replicated"
    resources:
      requests:
        memory: 64Mi
        cpu: 110m
