---
# Minimal Immich configuration for testing
immich:
  persistence:
    library:
      existingClaim: "immich-ephemeral-pvc"

postgresql:
  enabled: true
  auth:
    username: immich
    database: immich
  primary:
    persistence:
      enabled: false

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
