---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt"
    cert-manager.io/common-name: "argocd.internal.rmsz005.com"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - argocd.internal.rmsz005.com
    secretName: argocd-tls
  rules:
  - host: argocd.internal.rmsz005.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80