---
global:
  storageClass: "longhorn-ssd-replicated"

auth:
  database: bitwarden
  username: ""
  existingSecret: mssql-secret
  createDatabase: true

edition: "Developer"

primary:
  persistence:
    enabled: true
    storageClass: "longhorn-ssd-replicated"
    size: 20Gi
  
  resources:
    requests:
      memory: "1500Mi"
      cpu: "300m"
  
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  
  service:
    type: ClusterIP
    ports:
      mssql: 1433

