---
apache:
  replicaCount: 1
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx  # Uses existing NGINX Ingress
    hostname: hello-world.internal.rmsz005.com
    path: /
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
