---
# Benchmark ALL Storage Classes with Elasticsearch
# Results will be stored in Elasticsearch for later analysis
# Each benchmark: 1GB file × 2 jobs = 2GB needed, using 5GB PVC (safe margin)

---
# 1. local-path
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: bench2-local-path
  namespace: benchmark-operator
spec:
  cleanup: true
  elasticsearch:
    url: https://elastic:1BAg61MNY02o2Mps09or78BH@elasticsearch-es-http.elasticsearch.svc:9200
    verify_cert: false
  workload:
    name: "fio_distributed"
    args:
      prefill: false
      samples: 1
      servers: 1
      jobs: [write, read]
      bs: [64KiB]
      numjobs: [2]
      iodepth: [8]
      read_runtime: 30
      write_runtime: 30
      read_ramp_time: 5
      write_ramp_time: 5
      filesize: 1GiB
      storageclass: local-path
      storagesize: 5Gi

---
# 2. longhorn
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: bench2-longhorn
  namespace: benchmark-operator
spec:
  cleanup: true
  elasticsearch:
    url: https://elastic:1BAg61MNY02o2Mps09or78BH@elasticsearch-es-http.elasticsearch.svc:9200
    verify_cert: false
  workload:
    name: "fio_distributed"
    args:
      prefill: false
      samples: 1
      servers: 1
      jobs: [write, read]
      bs: [64KiB]
      numjobs: [2]
      iodepth: [8]
      read_runtime: 30
      write_runtime: 30
      read_ramp_time: 5
      write_ramp_time: 5
      filesize: 1GiB
      storageclass: longhorn
      storagesize: 5Gi

---
# 3. longhorn-hd-replicated
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: bench2-longhorn-hd-replicated
  namespace: benchmark-operator
spec:
  cleanup: true
  elasticsearch:
    url: https://elastic:1BAg61MNY02o2Mps09or78BH@elasticsearch-es-http.elasticsearch.svc:9200
    verify_cert: false
  workload:
    name: "fio_distributed"
    args:
      prefill: false
      samples: 1
      servers: 1
      jobs: [write, read]
      bs: [64KiB]
      numjobs: [2]
      iodepth: [8]
      read_runtime: 30
      write_runtime: 30
      read_ramp_time: 5
      write_ramp_time: 5
      filesize: 1GiB
      storageclass: longhorn-hd-replicated
      storagesize: 5Gi

---
# 4. longhorn-hd-single
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: bench2-longhorn-hd-single
  namespace: benchmark-operator
spec:
  cleanup: true
  elasticsearch:
    url: https://elastic:1BAg61MNY02o2Mps09or78BH@elasticsearch-es-http.elasticsearch.svc:9200
    verify_cert: false
  workload:
    name: "fio_distributed"
    args:
      prefill: false
      samples: 1
      servers: 1
      jobs: [write, read]
      bs: [64KiB]
      numjobs: [2]
      iodepth: [8]
      read_runtime: 30
      write_runtime: 30
      read_ramp_time: 5
      write_ramp_time: 5
      filesize: 1GiB
      storageclass: longhorn-hd-single
      storagesize: 5Gi

---
# 5. longhorn-hd-single-replica
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: bench2-longhorn-hd-single-replica
  namespace: benchmark-operator
spec:
  cleanup: true
  elasticsearch:
    url: https://elastic:1BAg61MNY02o2Mps09or78BH@elasticsearch-es-http.elasticsearch.svc:9200
    verify_cert: false
  workload:
    name: "fio_distributed"
    args:
      prefill: false
      samples: 1
      servers: 1
      jobs: [write, read]
      bs: [64KiB]
      numjobs: [2]
      iodepth: [8]
      read_runtime: 30
      write_runtime: 30
      read_ramp_time: 5
      write_ramp_time: 5
      filesize: 1GiB
      storageclass: longhorn-hd-single-replica
      storagesize: 5Gi

---
# 6. longhorn-nvme-replicated
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: bench2-longhorn-nvme-replicated
  namespace: benchmark-operator
spec:
  cleanup: true
  elasticsearch:
    url: https://elastic:1BAg61MNY02o2Mps09or78BH@elasticsearch-es-http.elasticsearch.svc:9200
    verify_cert: false
  workload:
    name: "fio_distributed"
    args:
      prefill: false
      samples: 1
      servers: 1
      jobs: [write, read]
      bs: [64KiB]
      numjobs: [2]
      iodepth: [8]
      read_runtime: 30
      write_runtime: 30
      read_ramp_time: 5
      write_ramp_time: 5
      filesize: 1GiB
      storageclass: longhorn-nvme-replicated
      storagesize: 5Gi

---
# 7. longhorn-ssd-replicated
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: bench2-longhorn-ssd-replicated
  namespace: benchmark-operator
spec:
  cleanup: true
  elasticsearch:
    url: https://elastic:1BAg61MNY02o2Mps09or78BH@elasticsearch-es-http.elasticsearch.svc:9200
    verify_cert: false
  workload:
    name: "fio_distributed"
    args:
      prefill: false
      samples: 1
      servers: 1
      jobs: [write, read]
      bs: [64KiB]
      numjobs: [2]
      iodepth: [8]
      read_runtime: 30
      write_runtime: 30
      read_ramp_time: 5
      write_ramp_time: 5
      filesize: 1GiB
      storageclass: longhorn-ssd-replicated
      storagesize: 5Gi

