---
# NVIDIA Device Plugin - Exposes nvidia.com/gpu resources to Kubernetes
# Deployed via ArgoCD - Only runs on nodes with label: gpu=nvidia

nvidia-device-plugin:
  # Node selector - only deploy on GPU-enabled nodes
  nodeSelector:
    gpu: nvidia

  # Resource limits for the device plugin itself
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

  # MIG (Multi-Instance GPU) strategy - not used for Quadro K620
  migStrategy: none
  
  # Update strategy
  updateStrategy:
    type: RollingUpdate

