librespeed:
  # Image configuration - using latest stable version
  image:
    repository: linuxserver/librespeed
    pullPolicy: IfNotPresent
    # Pinned to specific version (5.4.1-ls246, latest as of 2025-10-12)
    tag: "5.4.1-ls246"

  # Environment variables
  env:
    TZ: UTC
    PUID: "1001"
    PGID: "1001"
    # Optional: Set password for results page
    # PASSWORD: "your-password-here"
    # Optional: Database configuration for storing results
    # DB_TYPE: "mysql"
    # DB_NAME: "librespeed"
    # DB_HOSTNAME: "mysql.default.svc"
    # DB_USERNAME: "librespeed"
    # DB_PASSWORD: "password"
    # DB_PORT: "3306"

  # Service configuration
  service:
    main:
      ports:
        http:
          port: 80

  # Ingress configuration
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        # Allow large uploads for speed testing (50MB)
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        # Disable compression to ensure accurate speed measurements
        nginx.ingress.kubernetes.io/server-snippet: |
          gzip off;
      hosts:
        - host: speedtest.internal.rmsz005.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: speedtest-tls
          hosts:
            - speedtest.internal.rmsz005.com

  # Resource limits
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Persistence for storing test results (optional)
  persistence:
    config:
      enabled: false
      # Uncomment to enable persistence
      # enabled: true
      # mountPath: /config
      # storageClass: "longhorn"
      # accessMode: ReadWriteOnce
      # size: 1Gi

