---
# Bitwarden PostgreSQL Storage - 10GB SSD with replication
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-postgresql-pvc
  namespace: bitwarden
  labels:
    app: bitwarden-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-ssd-replicated
---
# Bitwarden Attachments Storage - 10GB HD with replication
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-attachments-pvc
  namespace: bitwarden
  labels:
    app: bitwarden
    component: attachments
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-hd-replicated

