---
# Bitwarden PostgreSQL Deployment
# Managed by ArgoCD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden-postgresql
  namespace: bitwarden
  labels:
    app: bitwarden-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden-postgresql
  template:
    metadata:
      labels:
        app: bitwarden-postgresql
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999  # postgres user
        fsGroup: 999
      containers:
      - name: postgresql
        image: postgres:16-alpine
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: bitwarden-postgresql-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitwarden-postgresql-secret
              key: password
        - name: POSTGRES_DB
          value: vault
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_INITDB_ARGS
          value: "--encoding=UTF8 --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "scram-sha-256"
        ports:
        - containerPort: 5432
          name: postgresql
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: bitwarden-postgresql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden-postgresql
  namespace: bitwarden
  labels:
    app: bitwarden-postgresql
spec:
  type: ClusterIP
  selector:
    app: bitwarden-postgresql
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql

