apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "excalidraw.fullname" . }}-nginx-config
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
data:
  nginx.conf: |
    upstream excalidraw_backend {
        server {{ include "excalidraw.fullname" . }}-backend:{{ .Values.excalidrawBackend.port }};
    }

    server {
        listen 80;
        server_name _;

        client_max_body_size 0;
        ssi on;
        ssi_types application/x-javascript application/javascript;

        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
        
        location ~ ^/(.well-known)/(.*)$ {
            add_header 'Access-Control-Allow-Origin' '*';
        }

        location / {
            include proxy_common_headers.conf;
            proxy_pass http://{{ include "excalidraw.fullname" . }};
            proxy_buffering off;
            proxy_redirect off;
        }

        location ~/api(.*)$ {
            include proxy_common_headers.conf;
            proxy_pass http://excalidraw_backend/api$1;
            proxy_buffering off;
        }

        location ^~ /api {
            include proxy_common_headers.conf;
            proxy_pass http://excalidraw_backend;
            proxy_buffering off;
        }

        location ~* \.io {
            include proxy_common_headers.conf;
            proxy_pass http://{{ include "excalidraw.fullname" . }}-room;
            proxy_redirect off;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

  proxy_common_headers.conf: |
    # Common proxy headers
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;

