apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "excalidraw.fullname" . }}
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "excalidraw.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "excalidraw.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: excalidraw
        image: "{{ .Values.excalidraw.image.repository }}:{{ .Values.excalidraw.image.tag }}"
        imagePullPolicy: {{ .Values.excalidraw.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: VITE_APP_STORAGE_BACKEND
          value: {{ .Values.excalidraw.env.storageBackend | quote }}
        - name: VITE_APP_HTTP_STORAGE_BACKEND_URL
          value: {{ .Values.excalidraw.env.httpStorageBackendUrl | quote }}
        - name: VITE_APP_BACKEND_V2_GET_URL
          value: {{ .Values.excalidraw.env.backendV2GetUrl | quote }}
        - name: VITE_APP_BACKEND_V2_POST_URL
          value: {{ .Values.excalidraw.env.backendV2PostUrl | quote }}
        - name: VITE_APP_WS_SERVER_URL
          value: {{ .Values.excalidraw.env.wsServerUrl | quote }}
        - name: VITE_APP_LIBRARY_URL
          value: {{ .Values.excalidraw.env.libraryUrl | quote }}
        - name: VITE_APP_LIBRARY_BACKEND
          value: {{ .Values.excalidraw.env.libraryBackend | quote }}
        - name: VITE_APP_PORTAL_URL
          value: {{ .Values.excalidraw.env.portalUrl | quote }}
        - name: VITE_APP_PLUS_APP
          value: {{ .Values.excalidraw.env.plusApp | quote }}
        - name: VITE_APP_PLUS_LP
          value: {{ .Values.excalidraw.env.plusLp | quote }}
        - name: VITE_APP_FIREBASE_CONFIG
          value: {{ .Values.excalidraw.env.firebaseConfig | quote }}
        - name: VITE_APP_DISABLE_TRACKING
          value: {{ .Values.excalidraw.env.disableTracking | quote }}
        - name: VITE_APP_COLLAPSE_OVERLAY
          value: {{ .Values.excalidraw.env.collapseOverlay | quote }}
        - name: VITE_APP_ENABLE_ESLINT
          value: {{ .Values.excalidraw.env.enableEslint | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.excalidraw.resources | nindent 10 }}

