---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw.fullname" . }}
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "excalidraw.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw.fullname" . }}-room
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
    app.kubernetes.io/component: room
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "excalidraw.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: room
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw.fullname" . }}-backend
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.excalidrawBackend.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "excalidraw.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw.fullname" . }}-nginx
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "excalidraw.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx

