---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: uptime-kuma
  annotations:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/important: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-nvme-replicated
  resources:
    requests:
      storage: 4Gi

