---
# PostgreSQL Deployment for Excalidraw
# Following the same pattern as immich-postgresql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw-postgresql
  namespace: excalidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw-postgresql
  template:
    metadata:
      labels:
        app: excalidraw-postgresql
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999  # postgres user
      containers:
      - name: postgresql
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_USER
          value: "excalidraw"
        - name: POSTGRES_PASSWORD
          value: "excalidraw"  # TODO: Move to sealed secret
        - name: POSTGRES_DB
          value: "excalidraw"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_INITDB_ARGS
          value: "--encoding=UTF8"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "scram-sha-256"
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: excalidraw-postgresql-pvc
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-postgresql
  namespace: excalidraw
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: excalidraw-postgresql
  type: ClusterIP
---
# PostgreSQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: excalidraw-postgresql-pvc
  namespace: excalidraw
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-ssd-replicated  # Using your existing storage class

