---
# Excalidraw Helm Chart Configuration

# Image configuration
image:
  repository: excalidraw/excalidraw
  pullPolicy: IfNotPresent
  tag: "v0.15.0"

# Replica count
replicaCount: 2

# Ingress configuration with TLS
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt"
    cert-manager.io/common-name: "excalidraw.internal.rmsz005.com"
  hosts:
    - host: excalidraw.internal.rmsz005.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - excalidraw.internal.rmsz005.com
      secretName: excalidraw-tls

# Resources
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Service configuration
service:
  type: ClusterIP
  port: 80

