apiVersion: v2
name: excalidraw-complete
description: A complete Helm chart for Excalidraw with collaboration room and storage backend
type: application
version: 1.0.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: "~12.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

