---
config:
  clients:
    - url: http://loki:3100/loki/api/v1/push
      tenant_id: ""
  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      pipeline_stages:
        - cri: {}
      relabel_configs:
        - source_labels:
            - __meta_kubernetes_pod_controller_name
          regex: ([0-9a-z-.]+)
          target_label: __tmp_controller_name
        - source_labels:
            - __meta_kubernetes_pod_namespace
          target_label: namespace
        - source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
        - source_labels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
          target_label: app
        - source_labels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_instance
          target_label: instance
        - source_labels:
            - __meta_kubernetes_pod_namespace
          regex: kube-system
          action: drop
        - source_labels:
            - __meta_kubernetes_pod_namespace
          regex: (immich|argocd|longhorn|metallb-system|cert-manager|n8n|default|monitoring)
          action: keep
        - source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
          target_label: __path__
          separator: /
          replacement: /var/log/pods/*$1/*.log
    - job_name: kubernetes-events
      kubernetes_sd_configs:
        - role: node
      static_configs:
        - targets:
            - localhost
          labels:
            job: kubernetes-events
            __path__: /var/log/events.log

daemonset:
  enabled: true

resources:
  requests:
    memory: "200Mi"
    cpu: "50m"
  limits:
    memory: "400Mi"
    cpu: "150m"

extraVolumes: []
extraVolumeMounts: []

serviceAccount:
  create: true

rbac:
  create: true
  pspEnabled: false

nodeSelector: {}
tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists

priorityClassName: ""

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 0

serviceMonitor:
  enabled: true
  interval: 30s
  additionalLabels: {}

defaultVolumes:
  - name: run
    hostPath:
      path: /run/promtail
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
  - name: pods
    hostPath:
      path: /var/log/pods
  - name: varlog
    hostPath:
      path: /var/log

defaultVolumeMounts:
  - name: run
    mountPath: /run/promtail
  - name: containers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: pods
    mountPath: /var/log/pods
    readOnly: true
  - name: varlog
    mountPath: /var/log
    readOnly: true
