namespace: kyverno

# Exclude namespaces at the webhook level (used by Helm templates)
admissionController:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kyverno
          - argocd

